version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3
  node: circleci/node@5.0.2
workflows:
  build:
    jobs:
      - cypress/run: # "run" job comes from "cypress" orb
          node-version: "18.17.0" # 필요한 Node.js 버전 지정
          start-command: "npm run start"
          pre-steps:
            - node/install:
                node-version: "18.17.0" # 필요한 Node.js 버전 설치
            - run:
                name: Check Node.js version
                command: node --version
