version: 2.1

orbs:
  cypress: cypress-io/cypress@3
  node: circleci/node@5.0.2 # Node orb 추가

workflows:
  build:
    jobs:
      - cypress/run:
          node-version: "18.17.0" # 필요한 Node.js 버전 지정
          start-command: "npm run start"
          pre-steps:
            - node/install:
                node-version: "18.17.0" # 필요한 Node.js 버전 설치
            - run:
                name: Check Node.js version
                command: node --version
